[package]
name = "search"
version = "0.1.3-beta"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "symbols"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.7", features = ["derive"] }
directories = "4.0.1"
open = "3.0.1"
scraper = "0.13.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tantivy = "0.18.0"
walkdir = "2.3.2"
